#!/usr/bin/env python
import sys, logging
from cli.parser.argumentparser import ArgumentParser
from core.action.add import AddAction

# parser = optparse.OptionParser(version="Baken 0.1.0")

# parser.add_option('-a', 'add', help='Adds a file or a directory to the baken repository', dest='add', default=False, action='store')
# parser.add_option('-d', 'delete', help='Deletes a file or a directory from the baken repository', dest='delete', default=False, action='store')
# parser.add_option('-m', 'move', help='Moves a file inside the baken repository', dest='move', action='store', nargs=2)

# (opts, args) = parser.parse_args()

# print opts.add
# print opts.delete
# print opts.move

def main(argv):

  logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)

  add_action = AddAction()

  parser = ArgumentParser({"add": add_action})
  parser.parse()
  add_action.run()

  sys.exit(0)

if __name__ == "__main__":

  main(sys.argv)
